### ISSUE TITLE
Should muacme create a new account?

### ISSUE THREAD

**Issue by prez** [jirutka/muacme#1]
```
muacme: uacme: failed to access /etc/ssl/uacme
````

**Comment by jirutka** [comment]
I don’t think that muacme should automatically create a new account. muacme is just a thin layer above uacme, you should use uacme to create a new account. I added a notice about this to the Readme (5025d4c875cc1267847e55c439cd85c48d404fa6).

**Comment by prez** [comment]
That works - thank you!
