### ISSUE TITLE
Use of `local` in the shell script

### ISSUE THREAD

**Issue by lunarnull** [jirutka/muacme#4]
I looked through the `muacme` shell script at the root of the repository and noticed that it uses the `local` keyword to mark certain variables.  It is unfortunately an extension to the POSIX sh standard and not defined therein.  It might be good to mention the fact in the readme, as is currently with `pipefail` (another extension).  Alternatively, the variable names could be prefixed with something like `_local_*` to minimize the chance of clashes.  But I suppose it is supported well enough throughout the implementations that a simple note in the readme will suffice.

**Comment by jirutka** [comment]
> I suppose it is supported well enough throughout the implementations that a simple note in the readme will suffice.

Yes, I don’t know about any POSIX-compliant shell implementation commonly used in this century as `/bin/sh` that don’t support `local`.
